### ISSUE TITLE
error G036AE10F: Required named parameter 'appearance' must be provided.

### ISSUE THREAD

**Issue by WBP20** [chan150/flutter_blue_plus_windows#5]
I got this error when trying to build the example app. 

../lib/src/windows/flutter_blue_plus_windows.dart(192,49): error G036AE10F: Required named parameter 'appearance' must be provided. [C:\Users\#\flutter_blue_plus_windows\example\build\windows\x64\flutter\flutter_assemble.vcxproj] 

Do you have any clue on how to solv this ?

**Comment by CamilleBrunin** [comment]
Hi, this is due to an update in Flutter_blue_plus library (release 1.31.15). Now you must provide an appearance parameter to the AdvertismentData class. I don't know what it means but you can just affect a random value to it in flutter_blue_plus_windows.dart, line 192. I set it to zero.

![image](https://github.com/chan150/flutter_blue_plus_windows/assets/56686608/2d2a0e78-0a0b-413b-87cd-50ab254fc0f2)

**Comment by CamilleBrunin** [comment]
(nevermind, bug has been fixed in last version of the library)
